services:
  - type: web
    name: hotel-reservation-api
    runtime: node
    repo: https://github.com/gonzaliaga/ReservasHotel-master
    plan: free
    envVars:
      - key: URL_BASE
        value: "https://reservashotel-nul0.onrender.com"
    region: oregon
    buildCommand: npm install
    startCommand: npm start
version: "1"
